/// <reference path="node_modules/@types/node/index.d.ts" />
/**
 * Generates playground/devtools/generated/spec-outline.mts from the
 * proposal-runtime-types spec.emu clause hierarchy.
 *
 * The spec source is resolved in this order:
 *   1. --spec <path> command line argument
 *   2. a sibling checkout at ../proposal-runtime-types/spec.emu
 *   3. https://raw.githubusercontent.com/sirisian/proposal-runtime-types/main/spec.emu
 *
 * The generated file is committed so the site builds without the spec repo
 * present. Re-run this script after spec.emu changes section structure, then
 * run scripts/validate-examples.mts to catch examples whose section ids no
 * longer exist.
 */
import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve } from "node:path";

const OUTPUT = resolve(import.meta.dirname, "../playground/devtools/generated/spec-outline.mts");
const SIBLING = resolve(import.meta.dirname, "../../proposal-runtime-types/spec.emu");
const RAW_URL = "https://raw.githubusercontent.com/sirisian/proposal-runtime-types/main/spec.emu";
const SPEC_BASE_URL = "https://sirisian.github.io/proposal-runtime-types/";

interface SpecSectionNode {
  id: string;
  title: string;
  children: SpecSectionNode[];
}

async function loadSpecSource(): Promise<{ source: string; origin: string }> {
  const argIndex = process.argv.indexOf("--spec");
  if (argIndex !== -1) {
    const path = process.argv[argIndex + 1];
    if (!path) throw new Error("--spec requires a path");
    return { source: await readFile(path, "utf8"), origin: path };
  }
  if (existsSync(SIBLING)) {
    return { source: await readFile(SIBLING, "utf8"), origin: SIBLING };
  }
  const response = await fetch(RAW_URL);
  if (!response.ok) throw new Error(`Failed to fetch ${RAW_URL}: ${response.status}`);
  return { source: await response.text(), origin: RAW_URL };
}

function cleanTitle(rawHTML: string): string {
  let text = rawHTML
    .replace(/<[^>]+>/g, "")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&")
    .replace(/_([A-Za-z][A-Za-z0-9]*)_/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
  // Abstract operation headings carry the full parameter list and return type,
  // e.g. `SameType ( s: a Type Record, t: a Type Record, ): a Boolean`. The
  // tree wants the operation name; the spec link has the details.
  const signature = /^([A-Za-z][A-Za-z0-9.%[\] ]*?)\s*\(.*\)\s*:\s+(a |an |either |~)/s;
  const match = text.match(signature);
  if (match) {
    text = `${match[1].trim()} ( )`;
  }
  return text;
}

function parseOutline(source: string): SpecSectionNode[] {
  const roots: SpecSectionNode[] = [];
  const stack: SpecSectionNode[] = [];
  const tag = /<(\/?)emu-clause([^>]*)>/g;
  let match: RegExpExecArray | null;
  while ((match = tag.exec(source)) !== null) {
    if (match[1] === "/") {
      if (stack.length === 0) throw new Error(`Unbalanced </emu-clause> at index ${match.index}`);
      stack.pop();
      continue;
    }
    const idMatch = match[2].match(/id="([^"]+)"/);
    if (!idMatch) throw new Error(`<emu-clause> without id at index ${match.index}`);
    const after = source.slice(match.index, match.index + 2000);
    const h1 = after.match(/<h1>([^]*?)<\/h1>/);
    const node: SpecSectionNode = {
      id: idMatch[1],
      title: h1 ? cleanTitle(h1[1]) : idMatch[1],
      children: [],
    };
    (stack.length === 0 ? roots : stack[stack.length - 1].children).push(node);
    stack.push(node);
  }
  if (stack.length !== 0) throw new Error(`Unclosed <emu-clause>: ${stack.map((n) => n.id).join(", ")}`);
  return roots;
}

function render(node: SpecSectionNode, indent: string): string {
  const title = JSON.stringify(node.title);
  if (node.children.length === 0) {
    return `${indent}{ id: ${JSON.stringify(node.id)}, title: ${title} }`;
  }
  const children = node.children.map((child) => render(child, indent + "  ")).join(",\n");
  return `${indent}{ id: ${JSON.stringify(node.id)}, title: ${title}, children: [\n${children},\n${indent}] }`;
}

const { source, origin } = await loadSpecSource();
const outline = parseOutline(source);
const count = (nodes: SpecSectionNode[]): number =>
  nodes.reduce((total, node) => total + 1 + count(node.children), 0);

const file = `// Generated by scripts/generate-spec-outline.mts - do not edit by hand.
// Source: ${origin.includes("://") ? origin : "proposal-runtime-types/spec.emu (local checkout)"}
// Sections: ${count(outline)}

export interface SpecSection {
  id: string;
  title: string;
  children?: SpecSection[];
}

export const SPEC_BASE_URL = ${JSON.stringify(SPEC_BASE_URL)};

export const SPEC_OUTLINE: SpecSection[] = [
${outline.map((node) => render(node, "  ")).join(",\n")},
];
`;

await writeFile(OUTPUT, file);
console.log(`Wrote ${count(outline)} sections from ${origin} to ${OUTPUT}`);
