import type { ExampleChapter } from "./types.mts";

/**
 * Composites (sec-composites and children) and Pattern Matching
 * (sec-pattern-matching and children). All outputs verified by
 * scripts/validate-examples.mts against the built engine.
 */
export const compositesAndMatching: ExampleChapter = [
  {
    section: "sec-composites",
    title: "Contents are identity",
    summary: "Two composites built from the same contents are the same object, whatever order they were written in.",
    code: "console.log(Composite({ x: 1, y: 4 }) === Composite({ y: 4, x: 1 }), Composite({ x: 1 }) === Composite({ x: 2 }));",
    expected: "true false",
  },
  {
    section: "sec-composite-objects",
    title: "Frozen, null-prototype, sorted keys",
    code: 'const c = Composite({ y: 1, x: 2, 2: 3, 1: 4 });\nconsole.log(Object.isFrozen(c), Object.getPrototypeOf(c), Object.keys(c).join(","));',
    expected: "true null '1,2,x,y'",
  },
  {
    section: "sec-composite-objects",
    title: "A composite tuple is an Array",
    code: "const t = Composite([1, 2, 3]);\nconsole.log(t.length, t[0], Array.isArray(t), Composite([1, 2]) === Composite([2, 1]));",
    expected: "3 1 true false",
  },
  {
    section: "sec-composite-types",
    title: "The element types are part of it",
    summary: "Composite.<T> creates at the type, so its elements are typed and it is a different composite from the untyped one.",
    code: "type T = [uint8, uint8];\nconsole.log(Reflect.typeOf(Composite.<T>([1, 2])[0]) === uint8, Composite.<T>([1, 2]) === Composite([uint8(1), uint8(2)]), Composite.<T>([1, 2]) === Composite([1, 2]));",
    expected: "true true false",
  },
  {
    section: "sec-composite-registry",
    title: "One entry per contents",
    summary: "The registry is what makes Set and Map treat equal composites as one key.",
    code: 'console.log(new Set([Composite({ x: 1 }), Composite({ x: 1 })]).size);\nconst m = new Map([[Composite({ x: 1, y: 4 }), "ship"]]);\nconsole.log(m.get(Composite({ y: 4, x: 1 })));',
    expected: "1\n'ship'",
  },
  {
    section: "sec-composite-abstract-operations",
    title: "Objects inside compare by identity",
    summary: "Interning is by contents, and a plain object's contents are its identity - so two fresh objects differ and one shared object matches.",
    code: "console.log(Composite({ v: {} }) === Composite({ v: {} }));\nconst o = {};\nconsole.log(Composite({ v: o }) === Composite({ v: o }));",
    expected: "false\ntrue",
  },
  {
    section: "sec-composite-function",
    title: "The function and its predicate",
    code: "console.log(Composite.isComposite(Composite({ x: 1 })), Composite.isComposite({}), Composite({ x: 1 }) instanceof Composite);",
    expected: "true false true",
  },
  {
    section: "sec-composite-json",
    title: "Composites serialize as their shape",
    code: "console.log(JSON.stringify(Composite({ x: 1 })), JSON.stringify(Composite([1, 2])));",
    expected: "'{\\\"x\\\":1}' '[1,2]'",
  },
  {
    section: "sec-composite-modifications",
    title: "Frozen means writes do nothing",
    summary: "The store is refused as on any frozen object; the composite is unchanged.",
    code: "const c = Composite({ x: 1 });\nc.x = 2;\nconsole.log(c.x);",
    expected: "1",
  },
  {
    section: "sec-composite-deviations",
    title: "A record and a tuple never coincide",
    summary: "The upstream proposal's two forms stay distinct here: same contents, different family, different object.",
    code: "console.log(Composite([1]) === Composite({ 0: 1 }), Array.isArray(Composite([1])), Array.isArray(Composite({ 0: 1 })));",
    expected: "false true false",
  },
  {
    section: "sec-iscomposite",
    title: "Testing for a composite",
    summary: "The predicate is the observable form of IsComposite - true for either family, false for an ordinary object.",
    code: "console.log(Composite.isComposite(Composite({ x: 1 })), Composite.isComposite(Composite([1])), Composite.isComposite({}));",
    expected: "true true false",
  },
  {
    section: "sec-canonicalizecompositevalue",
    title: "Element values canonicalize by type",
    summary: "A typed 1 and an untyped 1 are different contents, so they make different composites.",
    code: "console.log(Composite({ x: uint8(1) }) === Composite({ x: 1 }), Composite({ x: uint8(1) }) === Composite({ x: uint8(1) }), Composite({ x: uint8(1) }) === Composite({ x: uint16(1) }));",
    expected: "false true false",
  },
  {
    section: "sec-composite-entry-records",
    title: "Entries are key and value",
    code: 'const c = Composite({ x: 1, y: 2 });\nconsole.log(Object.entries(c).map(([k, v]) => k + "=" + v).join(","));',
    expected: "'x=1,y=2'",
  },
  {
    section: "sec-compositecanonicalorder",
    title: "Integer keys first, then strings in order",
    summary: "One canonical order is why two spellings of the same contents intern to one object.",
    code: 'console.log(Object.keys(Composite({ y: 1, x: 2, 2: 3, 1: 4 })).join(","));',
    expected: "'1,2,x,y'",
  },
  {
    section: "sec-compositefieldtype",
    title: "A field keeps its type",
    code: "type T = [uint8, uint8];\nconsole.log(Reflect.typeOf(Composite.<T>([1, 2])[0]) === uint8);",
    expected: "true",
  },
  {
    section: "sec-compositeshape",
    title: "Shape is the keys, not the values",
    summary: "Two composites of one shape stay distinct objects when their values differ.",
    code: 'const a = Composite({ x: 1 });\nconst b = Composite({ x: 2 });\nconsole.log(Object.keys(a).join(",") === Object.keys(b).join(","), a === b);',
    expected: "true false",
  },
  {
    section: "sec-findorcreatecomposite",
    title: "The second call finds the first",
    code: "console.log(Composite({ x: 1, y: 4 }) === Composite({ y: 4, x: 1 }));",
    expected: "true",
  },
  {
    section: "sec-findorcreatetuplecomposite",
    title: "Tuples intern by position",
    code: "console.log(Composite([1, 2]) === Composite([1, 2]), Composite([1, 2]) === Composite([2, 1]));",
    expected: "true false",
  },
  {
    section: "sec-compositematch",
    title: "Matching a composite against a pattern",
    summary: "CompositeMatch reads the composite's own entries, so a record pattern binds through it and a tuple pattern matches by position.",
    code: "console.log(match (Composite({ x: 1 })) { when { x: let v }: v; default: 0; });\nconsole.log(match (Composite([1, 2])) { when [1, let b]: b; default: 0; });",
    expected: "1\n2",
  },
  {
    section: "sec-composite-arg",
    title: "The source decides the family",
    summary: "An array source makes a tuple composite and an object source a record composite.",
    code: "console.log(Array.isArray(Composite([1])), Array.isArray(Composite({ 0: 1 })));",
    expected: "true false",
  },
  {
    section: "sec-composite-typeobject-call",
    title: "Calling a composite type object",
    summary: "Composite.<T> creates at the type, converting each element as it goes.",
    code: "interface I { x: uint8 }\nconsole.log(Reflect.typeOf(Composite.<I>({ x: 1 }).x) === uint8);",
    expected: "true",
  },
  {
    section: "sec-compositefromshape",
    title: "Built from a shape and its values",
    summary: "Creating at a type and creating from already-typed values reach the same interned object.",
    code: "type T = [uint8, uint8];\nconsole.log(Composite.<T>([1, 2]) === Composite([uint8(1), uint8(2)]));",
    expected: "true",
  },
  {
    section: "sec-composite.iscomposite",
    title: "What lives on Composite",
    code: 'console.log(Object.getOwnPropertyNames(Composite).join(","));',
    expected: "'length,name,isComposite'",
  },
  {
    section: "sec-composite-hasinstance",
    title: "instanceof Composite",
    code: "console.log(Composite({ x: 1 }) instanceof Composite, Composite([1]) instanceof Composite, {} instanceof Composite);",
    expected: "true true false",
  },
  {
    section: "sec-composite-custommatcher",
    title: "Composite as a pattern",
    summary: "The custom matcher makes Composite usable directly as a match arm.",
    code: 'console.log(Composite[Symbol.customMatcher](Composite({ x: 1 })), Composite[Symbol.customMatcher](1));\nconsole.log(match (Composite({ x: 1 })) { when Composite: "composite"; default: "no"; });',
    expected: "true false\n'composite'",
  },
  {
    section: "sec-composite-canbeheldweakly",
    title: "No weak identity",
    summary: "A composite is its contents, so there is nothing for a weak reference to observe the death of.",
    code: "new WeakRef(Composite({ x: 1 }));",
    throws: true,
    expected: "",
  },
  {
    section: "sec-composite-getiterator",
    title: "A tuple composite iterates",
    code: 'console.log([...Composite([1, 2, 3])].join("|"));',
    expected: "'1|2|3'",
  },
  {
    section: "sec-match-evaluation",
    title: "The subject is evaluated once",
    summary: "Arms are tried in order against one evaluation of the subject.",
    code: 'let n = 0;\nconst f = () => { n += 1; return 1; };\nconsole.log(match (f()) { when 1: "one"; default: "d"; }, n);',
    expected: "'one' 1",
  },
  {
    section: "sec-patternmatches",
    title: "A pattern is a test",
    summary: "The same pattern that selects an arm answers a boolean through is.",
    code: 'console.log([1, 2] is [let a, let b], match ([1, 2]) { when [let a, let b]: a + b; default: 0; });',
    expected: "true 3",
  },
  {
    section: "sec-match-structural",
    title: "Object patterns match by member",
    summary: "Absent members are ignored and a rest binding collects what the pattern did not name.",
    code: 'let out = "X";\nif (({ a: 1, b: 2, c: 3 }) is { a: 1, ...let rest }) { out = Object.keys(rest).join(","); }\nconsole.log(out);',
    expected: "'b,c'",
  },
  {
    section: "sec-match-array",
    title: "Array patterns match by position",
    code: 'console.log(match ([1, 9]) { when [1, let b]: b; default: 0; }, [1, 2] is [1, _]);',
    expected: "9 true",
  },
  {
    section: "sec-matchtypepattern",
    title: "A type pattern tests membership",
    code: 'console.log(uint8(1) is let x: uint8, 1 is let x: uint8);',
    expected: "true false",
  },
  {
    section: "sec-matchiteratorfill",
    title: "Filling from the subject",
    summary: "An array pattern draws only as many elements as it names, then binds the rest.",
    code: 'console.log(match ([1, 2, 3]) { when [let a, let b, let c]: a + b + c; default: 0; });',
    expected: "6",
  },
  {
    section: "sec-matchstructuraltype",
    title: "Composites match structurally",
    summary: "A composite is matched by its contents, so an ordinary object pattern reaches it.",
    code: 'console.log(Composite({ x: 1, y: 2 }) is { x: 1, y: let v } ? "matched" : "no", Composite([1, 2]) is [1, _]);',
    expected: "'matched' true",
  },
  {
    section: "sec-matchconstant",
    title: "A constant pattern",
    code: 'console.log(match (2) { when 1: "one"; when 2: "two"; default: "other"; });',
    expected: "'two'",
  },
  {
    section: "sec-matchrange",
    title: "A range pattern",
    code: 'console.log(match (5) { when 1..<3: "low"; when 4..<6: "mid"; default: "high"; });',
    expected: "'mid'",
  },
  {
    section: "sec-matchregexp",
    title: "A regular expression pattern",
    summary: "The pattern must match the whole subject, and a non-string never matches.",
    code: "console.log(\"aaa\" is /^a+$/, \"xaaay\" is /a+/, 1 is /1/);",
    expected: "true false false",
  },
  {
    section: "sec-match-exhaustiveness",
    title: "Covering a closed type",
    summary: "Every member of the enum has an arm, so no default is required.",
    code: 'enum Color { Red, Green }\nfunction name(c: Color) { return match (c) { when Color.Red: "red"; when Color.Green: "green"; }; }\nconsole.log(name(Color.Red), name(Color.Green));',
    expected: "'red' 'green'",
  },
  {
    section: "sec-pattern-matching",
    title: "match picks the first arm",
    code: 'console.log(match (2) { when 1: "one"; when 2: "two"; default: "other"; });',
    expected: "'two'",
  },
  {
    section: "sec-match-expression",
    title: "Ranges and guards as arms",
    code: 'console.log(match (5) { when 1..<3: "low"; when 4..<6: "mid"; default: "high"; });\nconsole.log(match (5) { when let x if (x > 3): "big"; default: "small"; });',
    expected: "'mid'\n'big'",
  },
  {
    section: "sec-match-patterns",
    title: "Structural patterns destructure",
    code: "console.log(match ({ a: 7 }) { when { a: let v }: v; default: 0; });\nconsole.log(match ([1, 9]) { when [1, let b]: b; default: 0; });",
    expected: "7\n9",
  },
  {
    section: "sec-match-patterns",
    title: "A binding may require a type",
    summary: "when let x: uint8 matches only a value of that type - an untyped 5 falls through.",
    code: 'console.log(match (uint8(5)) { when let x: uint8: "typed"; default: "no"; });\nconsole.log(match (5) { when let x: uint8: "typed"; default: "no"; });',
    expected: "'typed'\n'no'",
  },
  {
    section: "sec-pattern-static-semantics",
    title: "A match over a closed type needs no default",
    summary: "The arms cover every member of the enum, so the match is checked complete.",
    code: 'enum Color { Red, Green }\nfunction name(c: Color) { return match (c) { when Color.Red: "red"; when Color.Green: "green"; }; }\nconsole.log(name(Color.Red), name(Color.Green));',
    expected: "'red' 'green'",
  },
  {
    section: "sec-pattern-static-semantics",
    title: "Arms narrow the subject",
    summary: "Each arm's binding carries its matched type, so the string arm may take .length and the uint8 arm may do typed arithmetic.",
    code: 'let v: uint8 | string = "hi";\nconst r = match (v) { when let s: string: s.length; when let n: uint8: n + (1 := uint8); };\nconsole.log(r);',
    expected: "2",
  },
  {
    section: "sec-is-pattern",
    title: "is takes a pattern too",
    summary: "The binding form answers a boolean and binds in the branch it guards.",
    code: "console.log(uint8(1) is let x: uint8, 1 is let x: uint8, typeof (1 is 1));\nconst val = 5;\nlet out = \"X\";\nif (val is let x) { out = String(x); }\nconsole.log(out);",
    expected: "true false 'boolean'\n'5'",
  },
  {
    section: "sec-custommatcher-symbol",
    title: "An extractor pattern",
    summary: "The matcher returns the values the pattern binds, so Some(let inner) destructures through it.",
    code: "const Some = { [Symbol.customMatcher](v) { return [v]; } };\nconsole.log(match (7) { when Some(let inner): inner; default: 0; });",
    expected: "7",
  },
];
