import type { ExampleChapter } from "./types.mts";

/**
 * Functions and Overloading (sec-functions and children): signatures,
 * function-type identity and variance, overload resolution, named arguments,
 * return-type overloading, and annotations across the function forms. All
 * outputs verified by scripts/validate-examples.mts against the built engine.
 */
export const functions: ExampleChapter = [
  {
    section: "sec-functions",
    title: "Two bodies, one name",
    summary: "Declaring the name again adds a signature; the argument's type picks the body.",
    code: 'function f(x: uint8) { return "u8"; }\nfunction f(x: string) { return "str"; }\nconsole.log(f((1 := uint8)), f("hi"));',
    expected: "'u8' 'str'",
  },
  {
    section: "sec-signature-records",
    title: "A signature, reflected",
    summary: "A function type carries a list of Signature Records; reflection shows the parameters and return.",
    code: "type F = (a: uint8, b: string) => boolean;\nconst r = Reflect.getReflection(F);\nconsole.log(String(r.kind), r.signatures.length, r.signatures[0].parameters.length, r.signatures[0].return.type === boolean);",
    expected: "'function' 1 2 true",
  },
  {
    section: "sec-function-type-identity-and-subtyping",
    title: "Parameter names are not part of the type",
    code: "type F = (x: uint8) => void;\ntype G = (y: uint8) => void;\nconsole.log(F === G);",
    expected: "true",
  },
  {
    section: "sec-samefunctiontype",
    title: "The return type is",
    code: "type R1 = () => uint8;\ntype R2 = () => uint16;\nconsole.log(R1 === R2);",
    expected: "false",
  },
  {
    section: "sec-issignaturesubtype",
    title: "Parameters are contravariant",
    summary: "A function accepting the union serves anywhere one accepting the member is expected - not the reverse.",
    code: "type Wide = (x: uint8 | string) => void;\ntype Narrow = (x: uint8) => void;\nconsole.log(Reflect.isAssignable(Wide, Narrow), Reflect.isAssignable(Narrow, Wide));",
    expected: "true false",
  },
  {
    section: "sec-isfunctionsubtype",
    title: "Returns are covariant",
    summary: "A function promising the member can stand in for one promising the union.",
    code: "type R1 = () => uint8;\ntype R3 = () => (uint8 | string);\nconsole.log(Reflect.isAssignable(R1, R3), Reflect.isAssignable(R3, R1));",
    expected: "true false",
  },
  {
    section: "sec-overload-resolution",
    title: "The type selects the signature",
    summary: "A typed argument is not ranked; it goes to the signature its type is assignable to.",
    code: 'function width(x: uint8) { return "u8"; }\nfunction width(x: uint16) { return "u16"; }\nconsole.log(width((1 := uint8)), width((1 := uint16)));',
    expected: "'u8' 'u16'",
  },
  {
    section: "sec-resolveoverload",
    title: "No signature, no call",
    summary: "An argument no signature accepts is refused by the checker, before the program runs.",
    code: 'function f(x: uint8) { return "u"; }\nfunction f(x: string) { return "s"; }\nf(true);',
    throws: true,
    expected: "",
  },
  {
    section: "sec-named-arguments",
    title: "Arguments by name",
    code: 'function greet(first: string, last: string) { return first + " " + last; }\nconsole.log(greet(last: "Doe", first: "Jo"));',
    expected: "'Jo Doe'",
  },
  {
    section: "sec-named-arguments",
    title: "Positional and named mix",
    summary: "The named c lands on its parameter; the skipped b takes its default.",
    code: 'function f(a: uint32, b: string = "d", c: string = "e") { return b + c; }\nconsole.log(f(1, c: "C"));',
    expected: "'dC'",
  },
  {
    section: "sec-sequenceassignment",
    title: "Distribution around a default",
    summary: "Naming b lets SequenceAssignment give the optional a its default instead of the argument.",
    code: 'function f(a: string = "d", b: string) { return a + b; }\nconsole.log(f(b: "a"));',
    expected: "'da'",
  },
  {
    section: "sec-bindarguments",
    title: "A missing required parameter is refused",
    code: 'function g(option1: string, option2: string) {}\ng(option2: "a");',
    throws: true,
    expected: "",
  },
  {
    section: "sec-overloading-on-return-type",
    title: "No context, no answer",
    summary: "Two signatures differ only in return; a bare call gives the ranking nothing to decide with.",
    code: 'function make(): uint32 { return 1; }\nfunction make(): string { return "two"; }\nmake();',
    throws: true,
    expected: "",
  },
  {
    section: "sec-overloading-on-return-type",
    title: "The position decides",
    summary: "The binding's annotation is the contextual type, and it selects the signature.",
    code: 'function make(): uint32 { return 1; }\nfunction make(): string { return "two"; }\nconst s: string = make();\nconst n: uint32 = make();\nconsole.log(s, n);',
    expected: "'two' 1 (typed)",
  },
  {
    section: "sec-completing-the-literal-ranking",
    title: "number outranks float64",
    summary: "For a bare literal, the completed ranking puts the existing number type first.",
    code: 'function pick(x: float64) { return "f64"; }\nfunction pick(x: number) { return "num"; }\nconsole.log(pick(1));',
    expected: "'num'",
  },
  {
    section: "sec-typed-arrow-functions",
    title: "An annotated arrow",
    code: "const add = (a: uint8, b: uint8): uint8 => a + b;\nconsole.log(add(2, 3), add(2, 3) instanceof uint8);",
    expected: "5 (typed) true",
  },
  {
    section: "sec-annotations-on-the-remaining-function-forms",
    title: "A method takes the same annotation",
    code: "const o = { double(x: uint8): uint8 { return x + x; } };\nconsole.log(o.double(4));",
    expected: "8 (typed)",
  },
  {
    section: "sec-inferred-return-types",
    title: "A function's return type is inferred from what it returns",
    summary: "An unannotated return is not `any`: the checker reads the body and publishes what the function actually gives back, so a caller is checked against it.",
    code: "function f(a: uint8) { return a; }\nlet x: uint8 = f((5 := uint8));\nconsole.log(x);",
    expected: "5 (typed)",
  },
  {
    section: "sec-published-return-types",
    title: "The published type is what a caller is checked against",
    summary: "And it is named in the diagnostic, because a mismatch against an INFERRED type is otherwise hard to place - the annotation the reader is looking for is not written anywhere.",
    code: "function f(a: uint8) { return a; }\nlet s: string = f((5 := uint8));",
    throws: true,
    expected: "",
  },
  {
    section: "sec-inference-and-function-forms",
    title: "Every function form infers the same way",
    summary: "A declaration, a call through another function, and an arrow all publish a return type by the same rule - the form is not what decides it.",
    code: "function g(a: uint8) { return a; }\nfunction h(a: uint8) { return g(a); }\nconst k = (a: uint8) => a;\nlet y: uint8 = h((7 := uint8));\nlet z: uint8 = k((3 := uint8));\nconsole.log(y, z);",
    expected: "7 (typed) 3 (typed)",
  },
  {
    section: "sec-anchored-contributions",
    title: "An annotation anchors, an inference contributes",
    summary: "A written return type is the answer rather than a candidate: the body is checked AGAINST it instead of deciding it, which is what makes an annotated function a fixed point of the inference before it starts.",
    code: "function a(n: uint8): uint8 { return n; }\nfunction b(n: uint8) { return n; }\nlet p: uint8 = a((2 := uint8));\nlet q: uint8 = b((2 := uint8));\nconsole.log(p, q);",
    expected: "2 (typed) 2 (typed)",
  },
  {
    section: "sec-inference-fixpoint",
    title: "A recursive function still reaches an answer",
    summary: "The inference is a fixpoint computation, so a function that calls itself does not chase its own tail: the contributions that do not depend on the recursive call decide it.",
    code: "function count(n: uint8) {\n  if (n < (2 := uint8)) { return (1 := uint8); }\n  return n;\n}\nlet r: uint8 = count((3 := uint8));\nconsole.log(r);",
    expected: "3 (typed)",
  },
];
