import type { ExampleChapter } from "./types.mts";

/**
 * Generics (sec-generics and children): applications and their interning,
 * value parameters, specialization, where clauses, variance, and
 * higher-kinded parameters. All outputs verified by
 * scripts/validate-examples.mts against the built engine.
 */
export const generics: ExampleChapter = [
  {
    section: "sec-generics",
    title: "Applications intern like everything else",
    summary: "Box.<uint8> is one type wherever it is spelled, and a different one from Box.<uint16>.",
    code: "type Box<T> = { value: T };\ntype B8 = Box.<uint8>;\nconst b: B8 = { value: 5 };\nconsole.log(b.value, B8 === Box.<uint8>, Box.<uint8> === Box.<uint16>);",
    expected: "5 (typed) true false",
  },
  {
    section: "sec-generic-parameters-as-values",
    title: "A parameter can be a value",
    summary: "W: uint32 takes a value argument; methods and fields read it as an ordinary typed value.",
    code: "class Fixed<W: uint32> { size() { return W; } capacity = W; }\nconst f = new Fixed.<4>();\nconsole.log(f.size(), f.capacity);",
    expected: "4 (typed) 4 (typed)",
  },
  {
    section: "sec-generic-specialization",
    title: "A field takes the argument's type",
    summary: "Each application is a distinct type, so a field declared at a parameter holds what the application supplied - it defaults from that type and refuses what the type forbids, exactly as a concrete field does.",
    code: "class Box<T> { value: T; }\nconst b = new Box.<uint8>();\nconsole.log(b.value, b.value is uint8);\nb.value = 5;\nconsole.log(b.value, b.value is uint8);\nb.value = \"a string\";",
    throws: true,
    expected: "0 (typed) true\n5 (typed) true",
  },
  {
    section: "sec-generic-specialization",
    title: "Instantiations do not mix",
    summary: "Each application is a distinct type; A.<uint8> is not an A.<uint16>.",
    code: "class A<T> {}\nconst x: A.<uint16> = new A.<uint8>();",
    throws: true,
    expected: "",
  },
  {
    section: "sec-generic-where",
    title: "A where clause admits",
    code: "function only8<T>(x: T) where T === uint8 { return x; }\nconsole.log(only8.<uint8>((1 := uint8)) is uint8);",
    expected: "true",
  },
  {
    section: "sec-generic-where",
    title: "A where clause refuses the specialization",
    summary: "The clause is checked once the parameters are bound; a failing application is a type error against the clause.",
    code: "function only8<T>(x: T) where T === uint8 { return x; }\nonly8.<uint16>((1 := uint16));",
    throws: true,
    expected: "",
  },
  {
    section: "sec-generic-variance",
    title: "A declaration answers for its own claim",
    summary: "A structural type derives its variance and cannot be wrong; a declaration is a claim, so it is checked as an EARLY error - a covariant parameter in a writable field is refused before anything runs, since that position admits only an invariant one.",
    code: "interface Bad<out T> { value: T }",
    throws: true,
    expected: "",
  },
  {
    section: "sec-generic-variance",
    title: "A declared parameter relates its instantiations",
    summary: "`out` declares a parameter covariant and `in` contravariant, so two instantiations of one nominal declaration relate along that position - which structural types already did by inference and a nominal type could not express at all.",
    code: "interface P<out T> { get(): T }\ninterface H<in T> { put(v: T): void }\ninterface B<T> { get(): T }\nconsole.log(Reflect.isAssignable(type P.<uint8>, type P.<uint8 | string>), Reflect.isAssignable(type P.<uint8 | string>, type P.<uint8>));\nconsole.log(Reflect.isAssignable(type H.<uint8 | string>, type H.<uint8>), Reflect.isAssignable(type H.<uint8>, type H.<uint8 | string>));\nconsole.log(Reflect.isAssignable(type B.<uint8>, type B.<uint8 | string>));",
    expected: "true false\ntrue false\nfalse",
  },
  {
    section: "sec-generic-variance",
    title: "Invariance is the default",
    summary: "With no variance declared, instantiations relate only to themselves - and the structural form agrees, since a writable member is invariant.",
    code: "class Box<T> { constructor(v) { this.v = v; } }\nconsole.log(Reflect.isAssignable(type Box.<uint8>, type Box.<uint8>), Reflect.isAssignable(type Box.<uint8>, type Box.<uint16>));\ntype Narrow = { x: uint8 };\ntype Wide = { x: uint8 | string };\nconsole.log(Reflect.isAssignable(Narrow, Wide), Reflect.isAssignable(type { readonly x: uint8 }, type { readonly x: uint8 | string }));",
    expected: "true false\nfalse true",
  },
  {
    section: "sec-higher-kinded-parameters",
    title: "A parameter with a hole",
    summary: "W<_> declares a one-argument wrapper parameter with a generic default; the parameter stands for a declaration, not a type.",
    code: 'type Identity<T> = T;\ninterface I<W<_> = Identity> {}\nconsole.log("declared");',
    expected: "'declared'",
  },
  {
    section: "sec-bindtypearguments",
    title: "Named, positional, and defaulted arguments bind one way",
    summary: "BindTypeArguments takes a positional argument where one reaches the parameter, else the named one, else the default; the spellings name one specialization.",
    code: "type Grid<T = float64, Rows: uint32 = 4, Cols: uint32 = 4> = [].<T>;\nconsole.log(Grid.<Cols: 8> === Grid.<float64, 4, 8>, Grid.<uint8, Cols: 8> === Grid.<T: uint8, Rows: 4, Cols: 8>);",
    expected: "true true",
  },
  {
    section: "sec-bindtypearguments",
    title: "Named arguments may come in any order, and none may be followed by a positional one",
    summary: "A named list binds by name regardless of order; a positional argument after a named one is refused, since it no longer says which parameter it fills.",
    code: "type Grid<T = float64, Rows: uint32 = 4> = [].<T>;\ntype G = Grid.<Rows: 2, T: uint8>;\nconsole.log(G === Grid.<uint8, 2>);\ntype Bad = Grid.<Rows: 2, uint8>;",
    throws: true,
    expected: "true",
  },
  {
    section: "sec-variadic-parameters",
    title: "A type pack binds from the rest arguments",
    summary: "A pack is a tuple: `...Ts` bound from the trailing arguments, and the rest annotated with it collects exactly those.",
    code: "function count<...Ts>(...xs: Ts): uint32 { return xs.length; }\nconsole.log(count(1, \"a\", true), count());",
    expected: "3 (typed) 0 (typed)",
  },
  {
    section: "sec-variadic-parameters",
    title: "A value pack reads as its array, and a tuple type spreads into it",
    summary: "A value pack `...I: [].<uint32>` is bound from explicit arguments, reads as a frozen array in the body, and a tuple type spread supplies the same run.",
    code: "function lanes<...I: [].<uint32>>(): uint32 { return I.length; }\ntype Pair = [1, 0];\nconsole.log(lanes.<0, 1, 2>(), lanes.<...Pair>(), lanes.<>());",
    expected: "3 (typed) 2 (typed) 0 (typed)",
  },
  {
    section: "sec-variadic-parameters",
    title: "A where clause checks the pack per application",
    summary: "The predicate reads the pack as an array; an element that fails it refuses the application.",
    code: "function pick<...I: [].<uint32>>(): uint32 where I.every((i) => i < 4) { return I[0]; }\nconsole.log(pick.<3, 1>());\npick.<7>();",
    throws: true,
    expected: "3 (typed)",
  },
  {
    section: "sec-generic-function-values",
    title: "A specialization is a first-class, interned value",
    summary: "f.<uint8> in expression position is one function object per ordered bindings, whatever the spelling; it is callable later and its type is the instantiated signature.",
    code: "function id<T>(x: T): T { return x; }\nconst s = id.<uint8>;\nconsole.log(s === id.<uint8>, s === id.<T: uint8>, s !== id, s(3), String(Reflect.typeOf(s)));",
    expected: "true true true 3 (typed) '(x: uint.<8>) => uint.<8>'",
  },
  {
    section: "sec-generic-function-values",
    title: "A method specialization captures no receiver",
    summary: "obj.m.<3> is the method's specialization, receiver independent; a call supplies this as any member call does.",
    code: "class V { m<I: uint32>(): uint32 { return I; } }\nconst a = new V(); const b = new V();\nconsole.log(a.m.<3> === b.m.<3>, a.m.<3>.call(b));",
    expected: "true 3 (typed)",
  },
  {
    section: "sec-crossing-with-a-generic-function",
    title: "A generic function crosses into a generic slot up to renaming, and into a concrete one by instantiation",
    summary: "The slot's parameter names need not match the function's; a concrete slot takes the generic function as the instantiation that fits it.",
    code: "function id<T>(x: T): T { return x; }\nlet forward: <U>(x: U) => U = id;\nlet narrow: (x: uint8) => uint8 = id;\nconsole.log(forward(\"a\"), narrow(2 := uint8));",
    expected: "'a' 2 (typed)",
  },
  {
    section: "sec-crossing-with-a-generic-function",
    title: "A concrete function does not cross into a generic slot",
    summary: "A generic slot promises every instantiation; a function of one fixed parameter type cannot keep that promise, so the assignment is refused.",
    code: "let h: <T>(e: T) => void = (e: uint8): void => {};",
    throws: true,
    expected: "",
  },
];
