import type { ExampleChapter } from "./types.mts";

/**
 * Grammar (sec-type-grammar and children): the lexical additions, type
 * expressions and their operators, keyof, type parameters, annotations, and
 * types in expression position. All outputs verified by
 * scripts/validate-examples.mts against the built engine.
 */
export const grammar: ExampleChapter = [
  {
    section: "sec-type-grammar",
    title: "The type operator resolves the collision",
    summary: "An object type would read as a block in expression position; the type operator parses its operand as a type.",
    code: "console.log(typeof (type { x: uint8 }), typeof uint8);",
    expected: "'object' 'object'",
  },
  {
    section: "sec-lexical-grammar-for-types",
    title: "The lexicon coexists",
    summary: "Template literals are untouched, and := is one token converting its left operand.",
    code: 'console.log(`a${1}b`, ("s" := string));',
    expected: "'a1b' 's'",
  },
  {
    section: "sec-type-punctuators",
    title: "The .< and := punctuators",
    summary: ".< opens type arguments where < alone would compare; := converts in place.",
    code: 'function f() { return "seven"; }\nconsole.log(f.<uint8>(), (5 := uint8));',
    expected: "'seven' 5 (typed)",
  },
  {
    section: "sec-imaginary-literals",
    title: "The i suffix",
    summary: "The suffix attaches to any DecimalLiteral, and the value it denotes lies on the imaginary axis - so 4i is complex(0, 4). A following identifier start is still a syntax error, so 4if does not lex.",
    code: 'const a = 4i, b = 2.5i, c = 1e3i;\nconsole.log(a.toString(), b.toString(), c.toString());\nconsole.log(a.real, a.imaginary);',
    expected: "'4i' '2.5i' '1000i'\n0 4",
  },
  {
    section: "sec-input-element-type",
    title: "Comparison survives next door",
    summary: "The goal symbol keeps .< for type arguments and < for less-than in the same program.",
    code: 'const pairs = new Map.<string, uint8>();\npairs.set("a", 1);\nconsole.log(pairs.size, pairs.get("a"), 3 < 5);',
    expected: "1 1 (typed) true",
  },
  {
    section: "sec-type-expressions",
    title: "Forms compose",
    summary: "An array type unions with null; membership follows the composed type.",
    code: "type T = ([].<uint8>) | null;\nlet a: [].<uint8> = [1];\nconsole.log(a is T, null is T, [1] is T);",
    expected: "true true false",
  },
  {
    section: "sec-type-references",
    title: "A reference with arguments",
    summary: "Map.<string, uint8> is one type reference, usable in an alias and after new.",
    code: 'type Dict = Map.<string, uint8>;\nconst d: Dict = new Map.<string, uint8>();\nd.set("a", 1);\nconsole.log(d.get("a"));',
    expected: "1 (typed)",
  },
  {
    section: "sec-computed-types",
    title: "A call of a call",
    summary: "The spec's own phrase: a function returning a function that computes a type is still a type position.",
    code: "function id(T) { return T; }\nfunction wrap(T) { return id; }\ntype Q = wrap(uint8)(uint16);\nconsole.log(Q === uint16);",
    expected: "true",
  },
  {
    section: "sec-keyof",
    title: "The keys of an object type",
    code: 'type A = { a: uint8, b: string };\ntype K = keyof A;\nconsole.log("a" is K, "b" is K, "c" is K);',
    expected: "true true false",
  },
  {
    section: "sec-keytypesof",
    title: "An enum's keys live on typeof",
    summary: "keyof typeof C is the member names; keyof C is the keys of the member values, which have none.",
    code: 'enum C { Zero }\ntype K = keyof typeof C;\ntype V = keyof C;\nconsole.log("Zero" is K, "Zero" is V);',
    expected: "true false",
  },
  {
    section: "sec-array-and-tuple-types",
    title: "Extents and element lists",
    summary: "[2].<uint8> fixes the length; [uint8, string] fixes each position.",
    code: 'let f: [2].<uint8> = [1, 2];\nlet t: [uint8, string] = [1, "x"];\nconsole.log(f.length, t[1]);',
    expected: "2 (typed) 'x'",
  },
  {
    section: "sec-variance-static-semantics-early-errors",
    title: "A covariant parameter may not appear in an input position",
    summary: "The modifier is a promise about where the parameter may be read and written, so the declaration itself is checked: `out T` in a method PARAMETER would let a caller write through a wider view, and that is refused where it is written rather than where it would bite.",
    code: "interface P<out T> { put(v: T): void }",
    throws: true,
    expected: "",
  },
  {
    section: "sec-ordered-element-types",
    title: "A tuple's positions are ordered and its arity is exact",
    summary: "Each position has its own type, read in the order written, and the arity is part of the type - which is what a tuple has that an array of a union does not.",
    code: "let t: [uint8, string] = [1, \"s\"];\nconsole.log(t.length, t[0], t[1]);\nconsole.log(Reflect.getReflection(type [uint8, string]).kind);",
    expected: "2 1 (typed) 's'\n'tuple'",
  },
  {
    section: "sec-array-literal-static-type",
    title: "An array literal takes its type from its position",
    summary: "With no contextual type the literal is an ordinary array; at a typed position it is the typed array the position wants, and the elements convert at the boundary rather than after it.",
    code: "let plain = [1, 2, 3];\nconsole.log(Reflect.getReflection(Reflect.typeOf(plain)).kind);\nlet typed: [].<uint8> = [1, 2, 3];\nconsole.log(typed.length, typed[0]);",
    expected: "'array'\n3 (typed) 1 (typed)",
  },
  {
    section: "sec-object-types",
    title: "An object type asks what a value has",
    summary: "The structural form is what lets a value satisfy an interface by having its members, and it is consulted BEFORE the step that separates the kinds - without it the rules would refuse `f({ a: 1 })`, since an interface is a nominal type and an object literal\'s type is object. A class instance has its members too, so it reaches an object-typed position without declaring anything.",
    code: "interface IPoint { x: uint8 }\nclass Point { x: uint8 = 1; }\nfunction shape(p: { x: uint8 }) { return \"shape\"; }\nfunction contract(p: IPoint) { return \"contract\"; }\nlet o: { x: uint8 } = { x: (1 := uint8) };\nconsole.log(shape(new Point()), shape(o), contract(o));",
    expected: "'shape' 'shape' 'contract'",
  },
  {
    section: "sec-object-types",
    title: "An interface asks what a class promised",
    summary: "The other half of the same rule: an interface is nominal where a CLASS is related to it. `Point` has the members and never said so, and a class states a construction and an identity as well as a shape - it is the identity that its type is for. Saying `implements` is the whole of what it takes.",
    code: "interface IPoint { x: uint8 }\nclass Declared implements IPoint { x: uint8 = 1; }\nclass Point { x: uint8 = 1; }\nfunction contract(p: IPoint) { return \"contract\"; }\nconsole.log(contract(new Declared()));\ncontract(new Point());",
    throws: true,
    expected: "",
  },
  {
    section: "sec-object-types",
    title: "readonly is covariant in depth",
    summary: "The flag reflects, and a readonly member accepts a subtype where a writable one would not - which is sound because a value read from it is never written through it.",
    code: "type Src = { readonly x: uint8 };\ntype RO = { readonly x: uint8 | string };\nconsole.log(Reflect.getReflection(Src).properties[0].readonly, Reflect.isAssignable(Src, RO));",
    expected: "true true",
  },
  {
    section: "sec-object-types",
    title: "And the write it is never written through",
    summary: "That covariance rests on the write being refused, so it is - and by the checking pass, so the program never runs at all. The guarantee belongs to the view rather than the object: the same object seen through a writable type may still be assigned.",
    code: 'type R = { readonly x: uint8 };\nlet v: R = { x: 1 };\nconsole.log("never runs");\nv.x = (2 := uint8);',
    throws: true,
    expected: "",
  },
  {
    section: "sec-function-types",
    title: "Optional parameters",
    code: "type F = (a: uint8, b?: string) => void;\nconst s = Reflect.getReflection(F).signatures[0];\nconsole.log(s.parameters.length, s.parameters[1].optional);",
    expected: "2 true",
  },
  {
    section: "sec-type-parameters",
    title: "A parameter, inferred and explicit",
    summary: "T binds from the argument's element type, or explicitly with .<uint8>.",
    code: "function first<T>(items: [].<T>): T { return items[0]; }\nlet a: [].<uint8> = [7];\nconsole.log(first(a) is uint8, Number(first.<uint8>(a)));",
    expected: "true 7",
  },
  {
    section: "sec-computed-constraints",
    title: "A constraint admits",
    code: "function clamp<T extends uint8 | uint16>(x: T) { return x; }\nconsole.log(clamp((5 := uint8)) is uint8);",
    expected: "true",
  },
  {
    section: "sec-computed-constraints",
    title: "A constraint refuses",
    summary: "string is outside the constraint, so the call is a checker error.",
    code: 'function clamp<T extends uint8 | uint16>(x: T) { return x; }\nclamp("s");',
    throws: true,
    expected: "",
  },
  {
    section: "sec-type-annotations",
    title: "Annotations on fields and accessors",
    code: "class C {\n  x: uint8 = 3;\n  get double(): uint8 { return this.x + this.x; }\n}\nconsole.log(new C().double);",
    expected: "6 (typed)",
  },
  {
    section: "sec-types-in-expression-position",
    title: "A type name is an expression",
    summary: "uint8 is a value, since a type is a value.",
    code: "let t: type = uint8;\nconsole.log(t is type, (type) is type, 5 is type);",
    expected: "true true false",
  },
  {
    section: "sec-types-in-expression-position",
    title: "The operator resolves the collisions",
    summary: "A function type would read as an arrow, an object type as a block, a tuple as an array literal, and a union as a bitwise or - so the operator parses its operand as a type.",
    code: "type Fn = (uint8) => uint8;\ntype Obj = { x: uint8 };\ntype Tup = [uint8, uint8];\ntype Uni = uint8 | string;\nconsole.log((type (uint8) => uint8) === Fn, (type { x: uint8 }) === Obj, (type [uint8, uint8]) === Tup, (type uint8 | string) === Uni);",
    expected: "true true true true",
  },
  {
    section: "sec-types-in-expression-position",
    title: "A binding named type keeps its value reading",
    summary: "Where the operator claims a token, the program parenthesizes the name to mean the value instead - the trade the clause makes by leaving these operands to the operator.",
    code: 'const type = ["a", "b"];\nconsole.log((type)[0], (type).length);',
    expected: "'a' 2",
  },
  {
    section: "sec-types-in-expression-position",
    title: "A call is refined out of the cover",
    summary: "After the operator, parenthesized text could be a function type's parameters or a call's arguments; the token after the closing parenthesis decides, so a call of a function named type survives - named arguments included.",
    code: 'function type(x) { return "call:" + String(x === uint8); }\nconsole.log(type (uint8));\nconsole.log(type (x: uint8));',
    expected: "'call:true'\n'call:true'",
  },
  {
    section: "sec-types-in-expression-position",
    title: "Conversion and membership inline",
    code: 'console.log((3 := uint8) is uint8, 3 is uint8, "s" is uint8);',
    expected: "true false false",
  },
  {
    section: "sec-type-arguments-and-placement-new-in-expression-position",
    title: "Type arguments keep the receiver",
    summary: "o.m.<uint8>() is one member expression, so this stays bound (placement new pairs with the memory-layout chapter).",
    code: 'const o = { m() { return this === o ? "bound" : "lost"; } };\nconsole.log(o.m.<uint8>());',
    expected: "'bound'",
  },
];
