import type { ExampleChapter } from "./types.mts";

/**
 * The chapters between Decorators and Composites: declarative checker facts,
 * memory layout and its consumers, checked contracts, inference through
 * computed positions, operator declarations, vector comparisons, complex
 * numbers, ranges, structural matching, provenance, and the expansion
 * artifact. All outputs verified by scripts/validate-examples.mts.
 */
export const layoutAndMisc: ExampleChapter = [
  {
    section: "sec-deferred-applications",
    title: "A call carried as a type",
    summary: "pairOf(T) cannot evaluate while T is unbound, so it is carried and evaluated at the specialization - which is what lets it annotate a binding inside a generic body and mean a different type at each call.",
    code: 'function pairOf(T) { return Reflect.makeType({ kind: "tuple", elements: [{ type: T, rest: false }, { type: T, rest: false }] }); }\nconsole.log(pairOf(uint8) === (type [uint8, uint8]));\nfunction make<T>(x: T) { let p: pairOf(T); return p; }\nconsole.log(make((1 := uint8))[0], make("a")[0].length);',
    expected: "true\n0 (typed) 0",
  },
  {
    section: "sec-declarative-checker-facts",
    title: "The facts a signature carries",
    summary: "Beyond parameters and return, a signature carries the `this` it expects and what a call establishes. Neither has a source spelling, so a signature written as a type carries neither and one CONSTRUCTED carries what it was given - which is the point: these are facts a program states rather than ones the language computes.",
    code: "type F = (x: uint8) => boolean;\nconsole.log(Object.keys(Reflect.getReflection(F).signatures[0]).join(\",\"));\nconst G = Reflect.makeType({ kind: \"function\", signatures: [{ parameters: [{ name: \"v\", type: type any }], return: { type: type boolean }, narrows: [{ target: \"v\", type: type uint8 }] }] });\nconsole.log(Object.keys(Reflect.getReflection(G).signatures[0]).join(\",\"));",
    expected: "'parameters,return'\n'parameters,return,narrows'",
  },
  {
    section: "sec-this-adoption",
    title: "A method taken off its class",
    summary: "A method carries the `this` it expects, so taking one off its receiver is refused where the method is taken rather than where the loose function is called. The binding must be TYPED for the checker to see the method at all: an ordinary `const c = new Counter()` is `any` by design, and `:=` is the spelling that infers.",
    code: "class Counter { n: uint8 = 0; read(): uint8 { return this.n; } }\nlet c := new Counter();\nlet loose: () => uint8 = c.read;",
    throws: true,
    expected: "",
  },
  {
    section: "sec-declared-narrowing",
    title: "What a test establishes",
    summary: "A declared narrowing says of a call what `is` says of a test: the guard's signature carries [[Narrows]], and a call through a binding of that type narrows its argument in the branch the call guards. [[Narrows]] has no source spelling, so the guard type is constructed and reached through an alias.",
    code: "function makeGuard() { return Reflect.makeType({ kind: \"function\", signatures: [{ parameters: [{ name: \"v\", type: type any }], return: { type: type boolean }, narrows: [{ target: \"v\", type: type uint8 }] }] }); }\ntype Guard = makeGuard();\nconst isU8: Guard = (v) => typeof v === \"number\";\nlet box: uint8 | string = (5 := uint8);\nif (isU8(box)) { let n: uint8 = box; console.log(String(n)); }",
    expected: "'5'",
  },
  {
    section: "sec-memory-layout",
    title: "Types know their size",
    code: "console.log(uint8.bitLength, uint8.byteLength, float64.alignment);",
    expected: "8 1 8",
  },
  {
    section: "sec-layout-properties",
    title: "An arbitrary width describes itself",
    summary: "bitLength is exact; byteLength rounds up to a byte and then to the alignment.",
    code: "type U = uint.<4>;\nconsole.log(U.bitLength, U.byteLength);",
    expected: "4 1",
  },
  {
    section: "sec-natural-alignment",
    title: "Padding follows declaration order",
    summary: "The uint16 must land on an even offset, so a byte of padding sits after the uint8 and the class is four bytes.",
    code: "class N { a: uint8; b: uint16; }\nconsole.log((type N).byteLength, (type N).alignment);",
    expected: "4 2",
  },
  {
    section: "sec-layout-control",
    title: "packed removes the padding",
    summary: "The same fields with @packed are three bytes, and b sits at offset 1.",
    code: '@packed class A { a: uint8; b: uint16; }\nconsole.log((type A).byteLength, (type A).alignment, Reflect.getReflection.<Reflect.ClassFieldLayout, A>("b").offset);',
    expected: "3 1 1",
  },
  {
    section: "sec-layout-finiteness",
    title: "A layout must be finite",
    summary: "A value type class containing itself would demand infinite inline storage.",
    code: "class Cyclic { self: Cyclic; }",
    throws: true,
    expected: "",
  },
  {
    section: "sec-layout-finiteness",
    title: "The same rule reaches a type alias",
    summary: "The member is not a reference position, so the cycle would have to be laid out inline - the error names the field that closes it.",
    code: "type Bad = { self: Bad };",
    throws: true,
    expected: "",
  },
  {
    section: "sec-layout-finiteness",
    title: "A fixed extent stays inline",
    summary: "A dynamic array holds its elements out of line and admits the cycle; a fixed extent lays them inline and closes it.",
    code: "type Ok = { items: [].<Ok> };\nconsole.log(typeof Ok);\ntype Fixed = { items: [2].<Fixed> };",
    throws: true,
    expected: "'object'",
  },
  {
    section: "sec-capacity-operations",
    title: "Capacity is what is reserved, length is what is there",
    summary: "A growable typed array separates the two: `reserve` claims room without adding elements, so a push into reserved room copies nothing, and `shrinkToFit` gives the unused room back. Both are visible because the layout is - a typed array owns its storage.",
    code: "let a: [].<uint8> = [];\na.reserve(8);\nconsole.log(a.length, a.capacity);\na.push((1 := uint8));\nconsole.log(a.length, a.capacity);\na.shrinkToFit();\nconsole.log(a.length, a.capacity);",
    expected: "0 (typed) 8 (typed)\n1 (typed) 8 (typed)\n1 (typed) 1 (typed)",
  },
  {
    section: "sec-get-array.prototype.capacity",
    title: "capacity reads the storage, not the contents",
    summary: "The getter answers how many elements the storage holds room for, which is at least the length and may be more. It is of the index type, like `length`.",
    code: "let a: [].<uint8> = [];\na.reserve(4);\nconsole.log(a.capacity, a.length, a.capacity >= a.length);",
    expected: "4 (typed) 0 (typed) true",
  },
  {
    section: "sec-array.prototype.reserve",
    title: "reserve claims room and adds nothing",
    summary: "The length is untouched, so a `reserve` is invisible to anything that reads the array - it only decides whether the next push has to move the storage.",
    code: "let a: [].<uint8> = [];\na.push((1 := uint8));\na.reserve(16);\nconsole.log(a.length, a.capacity, a[0]);",
    expected: "1 (typed) 16 (typed) 1 (typed)",
  },
  {
    section: "sec-array.prototype.shrinktofit",
    title: "shrinkToFit gives the unused room back",
    summary: "The inverse of `reserve`: capacity comes down to the length, and the contents are unchanged. A program that has finished growing an array says so with this.",
    code: "let a: [].<uint8> = [];\na.reserve(32);\na.push((7 := uint8));\na.shrinkToFit();\nconsole.log(a.length, a.capacity, a[0]);",
    expected: "1 (typed) 1 (typed) 7 (typed)",
  },
  {
    section: "sec-array-type-withcapacity",
    title: "withCapacity builds the array already reserved",
    summary: "The same claim made at construction rather than after it, for the case where the size is known before the first element is.",
    code: "const a = [].<uint8>.withCapacity(4);\nconsole.log(a.length, a.capacity);",
    expected: "0 (typed) 4 (typed)",
  },
  {
    section: "sec-array-views",
    title: "A view over existing bytes",
    summary: "A Span aliases a buffer rather than copying it - the write lands in the original bytes, which is what makes a view a view. Constructed as `Span.<T>(buffer, byteOffset, count, byteElementLength)`: the element length is explicit so a view over a packed layout does not have to be inferred from the element type.",
    code: "const b = new ArrayBuffer(4);\nconst view = Span.<uint8>(b, 0, 4, 1);\nview[0] = (7 := uint8);\nconsole.log(b.byteLength, view[0], new Uint8Array(b)[0]);",
    expected: "4 7 (typed) 7",
  },
  {
    section: "sec-structure-of-arrays",
    title: "One array per field",
    summary: "An SoA stores columns; a ref loop writes through each element in place.",
    code: "class P { a: uint8; }\nconst s = new SoA.<P, 3>();\nfor (const ref p of s) { p.a = (7 := uint8); }\nconsole.log(s.length, s[0].a, s[2].a);",
    expected: "3 7 (typed) 7 (typed)",
  },
  {
    section: "sec-checked-contracts",
    title: "A where clause on a function",
    summary: "On an ordinary function the clause is the compile-time bound over its parameters, refused at the specialization.",
    code: "function only8<T>(x: T) where T === uint8 { return x; }\nonly8.<uint16>((1 := uint16));",
    throws: true,
    expected: "",
  },
  {
    section: "sec-inference-through-results",
    title: "Inference reads plain positions",
    summary: "T binds from the argument's own type; a parameter under a computed type would be opaque.",
    code: 'function id<T>(x: T): T { return x; }\nconsole.log(id((5 := uint8)) is uint8, id("s"));',
    expected: "true 's'",
  },
  {
    section: "sec-literal-freshness",
    title: "An undeclared property in a literal",
    summary: "An own property the type neither declares nor admits is refused, reported against the property - and refused by the checking pass, so nothing runs. Freshness belongs to the LITERAL, so the same object reaching the position through a binding is accepted by width subtyping.",
    code: "type Expected = { x: uint8 };\nconst viaBinding = { x: 1, extra: 2 };\nlet fine: Expected = viaBinding;\nconsole.log(\"the binding is fine:\", fine.x);\nlet bad: Expected = { x: 1, extra: 2 };",
    throws: true,
    expected: "",
  },
  {
    section: "sec-trial-specialization",
    title: "A closed candidate set",
    summary: "The union constraint gives a finite set to try, so each call binds T from its argument.",
    code: 'function pick<T extends uint8 | string>(x: T) { return x; }\nconsole.log(pick((1 := uint8)) is uint8, pick("s"));',
    expected: "true 's'",
  },
  {
    section: "sec-declared-inverses",
    title: "Inference of last resort",
    summary: "Where ordinary inference and trial both fail, an explicit type argument always works.",
    code: "function id<T>(x: T): T { return x; }\nconsole.log(id.<uint16>((1 := uint16)) is uint16);",
    expected: "true",
  },
  {
    section: "sec-operator-declarations",
    title: "Declared on a class, and appended later",
    summary: "The partial declaration reopens the class and adds an operator to it.",
    code: "class Money { constructor(c) { this.c = c; } operator+(rhs: Money) { return new Money(this.c + rhs.c); } }\nconsole.log((new Money(2) + new Money(3)).c);\npartial class Money { operator-(rhs: Money) { return new Money(this.c - rhs.c); } }\nconsole.log((new Money(5) - new Money(2)).c);",
    expected: "5\n3",
  },
  {
    section: "sec-vector-comparisons",
    title: "The expected type picks the result, and there are three",
    summary: "Overloaded on its return type. The clause defines exactly three results - the WIDE MASK, a boolean vector of the compared width; the COMPACT MASK, one bit per lane; and the COMPARED VECTOR TYPE itself, matching lanes all-ones. A `boolean` is not among them, and with no expected type at all the expression is ambiguous and is a type error, which is why the result type is written.",
    code: "const m: boolean32x4 = float32x4(1, 2, 3, 4) < float32x4(4, 3, 2, 1);\nconsole.log(m.any(), m.all());\nconst c: uint8 = float32x4(1, 1, 1, 1) == float32x4(1, 1, 1, 1);\nconsole.log(c);",
    expected: "true false\n15 (typed)",
  },
  {
    section: "sec-complex-numbers",
    title: "The type, and the extension that completes it",
    summary: "This document delivers the type, the literal and the conversions; the operators and the Math additions come from the extension the hooks table names, whose arithmetic is C99 Annex G's over the components.",
    code: "console.log(typeof complex64, (type complex128).byteLength);\nconsole.log((complex(3, 4) * complex(1, 2)).toString(), Math.conj(complex(3, 4)).toString());",
    expected: "'object' 16\n'-5+10i' '3-4i'",
  },
  {
    section: "sec-ranges",
    title: "A range is a value",
    code: "const r = 1..<6;\nconsole.log(r.start, r.end, (..).isFull);",
    expected: "1 6 true",
  },
  {
    section: "sec-range-literals",
    title: "The .. family, and what it does not break",
    summary: "Open-ended forms omit an endpoint; the existing operators next door are untouched.",
    code: "console.log((5..).end, 1 <= 2, 1 << 2, 1 < .5);",
    expected: "undefined true 4 false",
  },
  {
    section: "sec-structural-matching",
    title: "inferSlot and matchType (not yet in the engine)",
    summary: "The clause calls this operation optional, and the engine defers it - its conformance matrix lists both by name.",
    code: "console.log(typeof Reflect.inferSlot, typeof Reflect.matchType);",
    expected: "'undefined' 'undefined'",
  },
  {
    section: "sec-provenance",
    title: "Origins are not part of identity",
    summary: "Provenance is a host-facing channel; the reflected origin property is deliberately absent, and identity never reads it.",
    code: "type A = { x: uint8 };\ntype B = { x: uint8 };\nconst r = Reflect.getReflection(A);\nconsole.log(A === B, \"origin\" in r.properties[0]);",
    expected: "true false",
  },
  {
    section: "sec-expansion-artifact",
    title: "Interning is what makes it shippable",
    summary: "The artifact serializes the interning table; the property it rests on is that one type computed twice is one object.",
    code: "function id(T) { return T; }\ntype Q1 = id(uint8);\ntype Q2 = id(uint8);\nconsole.log(Q1 === Q2, Q1 === uint8);",
    expected: "true true",
  },
];
