import type { ExampleChapter } from "./types.mts";

/**
 * The chapters between Decorators and Composites: declarative checker facts,
 * memory layout and its consumers, checked contracts, inference through
 * computed positions, operator declarations, vector comparisons, complex
 * numbers, ranges, structural matching, provenance, and the expansion
 * artifact. All outputs verified by scripts/validate-examples.mts.
 */
export const layoutAndMisc: ExampleChapter = [
  {
    section: "sec-deferred-applications",
    title: "A call carried as a type",
    summary: "pairOf(T) cannot evaluate while T is unbound, so it is carried and evaluated at the specialization (the deferred result is not usable as a binding's type yet: KNOWN-DIVERGENCES.md D15).",
    code: 'function pairOf(T) { return Reflect.makeType({ kind: "tuple", elements: [{ type: T, rest: false }, { type: T, rest: false }] }); }\ntype P8 = pairOf(uint8);\ntype Expected = [uint8, uint8];\nconsole.log(P8 === Expected);',
    expected: "true",
  },
  {
    section: "sec-declarative-checker-facts",
    title: "The facts a signature carries",
    summary: "Beyond parameters and return, a signature is specified to carry the this it expects and what a call establishes; the engine's records carry neither (KNOWN-DIVERGENCES.md D17).",
    code: "type F = (x: uint8) => boolean;\nconst s = Reflect.getReflection(F).signatures[0];\nconsole.log(Object.keys(s).join(\",\"));",
    expected: "'parameters,return'",
  },
  {
    section: "sec-this-adoption",
    title: "A method taken off its class",
    summary: "The extraction should be a type error at the boundary that took the method; without [[ThisType]] the engine lets it through and fails inside the body instead (D17).",
    code: "class Counter { n: uint8 = 0; read() { return this.n; } }\nconst c = new Counter();\nconsole.log(c.read());\nconst loose = c.read;\nloose();",
    throws: true,
    expected: "0 (typed)",
  },
  {
    section: "sec-declared-narrowing",
    title: "What a test establishes",
    summary: "A declared narrowing says of a call what the built-in is test says here; the declared form has no engine support yet (D17).",
    code: "let v: uint8 | string = (5 := uint8);\nif (v is uint8) { console.log(v + (1 := uint8)); }",
    expected: "6 (typed)",
  },
  {
    section: "sec-memory-layout",
    title: "Types know their size",
    code: "console.log(uint8.bitLength, uint8.byteLength, float64.alignment);",
    expected: "8 1 8",
  },
  {
    section: "sec-layout-properties",
    title: "An arbitrary width describes itself",
    summary: "bitLength is exact; byteLength rounds up to a byte and then to the alignment.",
    code: "type U = uint.<4>;\nconsole.log(U.bitLength, U.byteLength);",
    expected: "4 1",
  },
  {
    section: "sec-natural-alignment",
    title: "Padding follows declaration order",
    summary: "The uint16 must land on an even offset, so a byte of padding sits after the uint8 and the class is four bytes.",
    code: "class N { a: uint8; b: uint16; }\nconsole.log((type N).byteLength, (type N).alignment);",
    expected: "4 2",
  },
  {
    section: "sec-layout-control",
    title: "packed removes the padding",
    summary: "The same fields with @packed are three bytes, and b sits at offset 1.",
    code: '@packed class A { a: uint8; b: uint16; }\nconsole.log((type A).byteLength, (type A).alignment, Reflect.getReflection.<Reflect.ClassFieldLayout, A>("b").offset);',
    expected: "3 1 1",
  },
  {
    section: "sec-layout-finiteness",
    title: "A layout must be finite",
    summary: "A value type class containing itself would demand infinite inline storage.",
    code: "class Cyclic { self: Cyclic; }",
    throws: true,
    expected: "",
  },
  {
    section: "sec-layout-finiteness",
    title: "The same rule reaches a type alias",
    summary: "The member is not a reference position, so the cycle would have to be laid out inline - the error names the field that closes it.",
    code: "type Bad = { self: Bad };",
    throws: true,
    expected: "",
  },
  {
    section: "sec-layout-finiteness",
    title: "A fixed extent stays inline",
    summary: "A dynamic array holds its elements out of line and admits the cycle; a fixed extent lays them inline and closes it.",
    code: "type Ok = { items: [].<Ok> };\nconsole.log(typeof Ok);\ntype Fixed = { items: [2].<Fixed> };",
    throws: true,
    expected: "'object'",
  },
  {
    section: "sec-array-views",
    title: "A view over existing bytes",
    summary: "Calling the array type on a buffer aliases it - the write lands in the original bytes.",
    code: "const b = new ArrayBuffer(4);\nconst view = [].<uint8>(b);\nview[0] = (7 := uint8);\nconsole.log(view.length, view[0], new Uint8Array(b)[0]);",
    expected: "4 7 (typed) 7",
  },
  {
    section: "sec-structure-of-arrays",
    title: "One array per field",
    summary: "An SoA stores columns; a ref loop writes through each element in place.",
    code: "class P { a: uint8; }\nconst s = new SoA.<P, 3>();\nfor (const ref p of s) { p.a = (7 := uint8); }\nconsole.log(s.length, s[0].a, s[2].a);",
    expected: "3 7 (typed) 7 (typed)",
  },
  {
    section: "sec-checked-contracts",
    title: "A where clause on a function",
    summary: "On an ordinary function the clause is the compile-time bound over its parameters, refused at the specialization.",
    code: "function only8<T>(x: T) where T === uint8 { return x; }\nonly8.<uint16>((1 := uint16));",
    throws: true,
    expected: "",
  },
  {
    section: "sec-inference-through-results",
    title: "Inference reads plain positions",
    summary: "T binds from the argument's own type; a parameter under a computed type would be opaque.",
    code: 'function id<T>(x: T): T { return x; }\nconsole.log(id((5 := uint8)) is uint8, id("s"));',
    expected: "true 's'",
  },
  {
    section: "sec-literal-freshness",
    title: "An undeclared property in a literal",
    summary: "The spec makes an extra own property a type error against the literal; the engine accepts it (KNOWN-DIVERGENCES.md D16).",
    code: "type Expected = { x: uint8 };\nlet ok: Expected = { x: 1 };\nconsole.log(ok.x);",
    expected: "1 (typed)",
  },
  {
    section: "sec-trial-specialization",
    title: "A closed candidate set",
    summary: "The union constraint gives a finite set to try, so each call binds T from its argument.",
    code: 'function pick<T extends uint8 | string>(x: T) { return x; }\nconsole.log(pick((1 := uint8)) is uint8, pick("s"));',
    expected: "true 's'",
  },
  {
    section: "sec-declared-inverses",
    title: "Inference of last resort",
    summary: "Where ordinary inference and trial both fail, an explicit type argument always works.",
    code: "function id<T>(x: T): T { return x; }\nconsole.log(id.<uint16>((1 := uint16)) is uint16);",
    expected: "true",
  },
  {
    section: "sec-operator-declarations",
    title: "Declared on a class, and appended later",
    summary: "The partial declaration reopens the class and adds an operator to it.",
    code: "class Money { constructor(c) { this.c = c; } operator+(rhs: Money) { return new Money(this.c + rhs.c); } }\nconsole.log((new Money(2) + new Money(3)).c);\npartial class Money { operator-(rhs: Money) { return new Money(this.c - rhs.c); } }\nconsole.log((new Money(5) - new Money(2)).c);",
    expected: "5\n3",
  },
  {
    section: "sec-vector-comparisons",
    title: "The expected type picks the result",
    summary: "Overloaded on its return: a boolean32x4 position yields the lane mask, a boolean position the reduced answer.",
    code: "const m: boolean32x4 = float32x4(1, 2, 3, 4) < float32x4(4, 3, 2, 1);\nconsole.log(m.any(), m.all());\nconst b: boolean = float32x4(1, 1, 1, 1) == float32x4(1, 1, 1, 1);\nconsole.log(b);",
    expected: "true false\ntrue",
  },
  {
    section: "sec-complex-numbers",
    title: "What the extension delivers, and what it owes",
    summary: "The type, the literal and the conversions are this document's; the operators and the Math additions are the extension's, and the hooks table is a map of obligations rather than a specification of them (KNOWN-DIVERGENCES.md D10).",
    code: "console.log(typeof complex64, (type complex128).byteLength, typeof Math.conj);",
    expected: "'object' 16 'undefined'",
  },
  {
    section: "sec-ranges",
    title: "A range is a value",
    code: "const r = 1..<6;\nconsole.log(r.start, r.end, (..).isFull);",
    expected: "1 6 true",
  },
  {
    section: "sec-range-literals",
    title: "The .. family, and what it does not break",
    summary: "Open-ended forms omit an endpoint; the existing operators next door are untouched.",
    code: "console.log((5..).end, 1 <= 2, 1 << 2, 1 < .5);",
    expected: "undefined true 4 false",
  },
  {
    section: "sec-structural-matching",
    title: "inferSlot and matchType (not yet in the engine)",
    summary: "The clause calls this operation optional, and the engine defers it - its conformance matrix lists both by name.",
    code: "console.log(typeof Reflect.inferSlot, typeof Reflect.matchType);",
    expected: "'undefined' 'undefined'",
  },
  {
    section: "sec-provenance",
    title: "Origins are not part of identity",
    summary: "Provenance is a host-facing channel; the reflected origin property is deliberately absent, and identity never reads it.",
    code: "type A = { x: uint8 };\ntype B = { x: uint8 };\nconst r = Reflect.getReflection(A);\nconsole.log(A === B, \"origin\" in r.properties[0]);",
    expected: "true false",
  },
  {
    section: "sec-expansion-artifact",
    title: "Interning is what makes it shippable",
    summary: "The artifact serializes the interning table; the property it rests on is that one type computed twice is one object.",
    code: "function id(T) { return T; }\ntype Q1 = id(uint8);\ntype Q2 = id(uint8);\nconsole.log(Q1 === Q2, Q1 === uint8);",
    expected: "true true",
  },
];
