import type { ExampleChapter } from "./types.mts";

/**
 * Threading (sec-threading and children). The playground runs one agent, so
 * the sections about a second thread observing the first demonstrate the
 * surface and the single-agent semantics rather than a race; each says so.
 * All outputs verified by scripts/validate-examples.mts.
 */
export const threading: ExampleChapter = [
  {
    section: "sec-threading",
    title: "The threading surface",
    code: "function body() { return 7; }\nconsole.log(typeof body.callThread, typeof Thread, typeof Lock, typeof Condition);",
    expected: "'function' 'object' 'function' 'function'",
  },
  {
    section: "sec-threading-agent-cluster",
    title: "One heap, many agents",
    summary: "A spawned thread is a new agent of the same cluster sharing one heap: the object the body mutated is the very object here, not a copy. (The playground runs one agent, so the body simply runs on it.)",
    code: "globalThis.shared = { count: 0 };\nfunction body() { shared.count += 1; return shared.count; }\nbody.callThread();\nconsole.log(typeof shared, shared.count);",
    expected: "'object' 1",
  },
  {
    section: "sec-threading-scheduling",
    title: "A handle is an ordinary promise",
    summary: "callThread answers a promise, so the reaction is an ordinary job - no special case in the scheduler.",
    code: "function body() { return 7; }\nconst handle = body.callThread();\nconsole.log(handle instanceof Promise, typeof handle.then);",
    expected: "true 'function'",
  },
  {
    section: "sec-finalizationregistry-across-threads",
    title: "Registries stay on their thread",
    summary: "A FinalizationRegistry's callbacks run as jobs of the agent that made it, which is what keeps its bookkeeping coherent.",
    code: "const r = new FinalizationRegistry(() => {});\nconsole.log(typeof r.register, typeof r.unregister);",
    expected: "'function' 'function'",
  },
  {
    section: "sec-threading-callthread",
    title: "Arguments are forwarded",
    summary: "The call classifies its arguments and forwards them; the result arrives through the handle.",
    code: "function body(a, b) { return a + b; }\nconst handle = body.callThread(2, 3);\nconsole.log(typeof handle.then, body(2, 3));",
    expected: "'function' 5",
  },
  {
    section: "sec-function.prototype.callthread",
    title: "callThread is on every function",
    code: "const arrow = () => 1;\nconsole.log(typeof arrow.callThread, typeof (function () {}).callThread, arrow.callThread === Function.prototype.callThread);",
    expected: "'function' 'function' true",
  },
  {
    section: "sec-classifythreadarguments",
    title: "What may cross",
    summary: "Value-type arguments are copied and shared references stay shared; a plain object crosses because the heap is one.",
    code: "function body(n) { return n; }\nlet v: uint32 = 5;\nconsole.log(typeof body.callThread(v).then, typeof body.callThread({ a: 1 }).then);",
    expected: "'function' 'function'",
  },
  {
    section: "sec-createthread",
    title: "Creating the thread",
    summary: "Each call creates an agent of the cluster; the handles are distinct promises.",
    code: "function body() { return 1; }\nconst a = body.callThread();\nconst b = body.callThread();\nconsole.log(a !== b, a instanceof Promise && b instanceof Promise);",
    expected: "true true",
  },
  {
    section: "sec-thread-cancellation",
    title: "Cancellation rides on AbortSignal",
    summary: "The proposal defers to the WHATWG object rather than defining one, and reads its aborted state and reason.",
    code: 'const c = new AbortController();\nconsole.log(c.signal.aborted);\nc.abort("done");\nconsole.log(c.signal.aborted, c.signal.reason);',
    expected: "false\ntrue 'done'",
  },
  {
    section: "sec-threading-shared-modifier",
    title: "shared is a type constructor",
    code: "type S = shared uint32;\nconsole.log(Reflect.getReflection(S).kind);",
    expected: "'shared'",
  },
  {
    section: "sec-shared-storage",
    title: "A shared binding holds an ordinary typed value",
    summary: "The modifier changes where the storage lives, not what the value is.",
    code: "let a: shared uint32 = 5;\nconsole.log(a, a instanceof uint32);",
    expected: "5 (typed) true",
  },
  {
    section: "sec-shared-stability",
    title: "shared applies across the families",
    summary: "Scalars, booleans, and fixed arrays may all be shared - the requirement is a stable layout.",
    code: "console.log(Reflect.getReflection(type shared float64).kind, Reflect.getReflection(type shared boolean).kind, Reflect.getReflection(type shared [4].<uint8>).kind);",
    expected: "'shared' 'shared' 'shared'",
  },
  {
    section: "sec-threading-memory-model",
    title: "Atomic operations are the ordering tool",
    summary: "The memory model is the existing one extended to typed storage; atomics are how a program orders accesses within it.",
    code: "let a: uint32 = 7;\nconsole.log(Atomics.load(ref a));\nAtomics.store(ref a, 9);\nconsole.log(a);",
    expected: "7 (typed)\n9 (typed)",
  },
  {
    section: "sec-threading-atomics",
    title: "Atomics on a typed binding",
    code: "let a: uint32 = 5;\nAtomics.add(ref a, 3);\nconsole.log(a);",
    expected: "8 (typed)",
  },
  {
    section: "sec-atomics-reference-arguments",
    title: "The target is a reference",
    summary: "Atomics take a ref to the location rather than a buffer and an index, so any typed binding qualifies.",
    code: "let a: uint32 = 1;\nconst old = Atomics.exchange(ref a, 2);\nconsole.log(old, a);",
    expected: "1 (typed) 2 (typed)",
  },
  {
    section: "sec-validateatomictarget",
    title: "shared and unshared both qualify",
    summary: "The operation validates the location's type, not whether it is shared - an unshared binding is simply uncontended.",
    code: "let s: shared uint32 = 5;\nAtomics.add(ref s, 3);\nlet u: uint32 = 5;\nAtomics.add(ref u, 3);\nconsole.log(s, u);",
    expected: "8 (typed) 8 (typed)",
  },
  {
    section: "sec-atomics-typed-operations",
    title: "Bitwise atomics",
    code: "let b: uint8 = 0b1100;\nAtomics.and(ref b, 0b1010);\nconsole.log(b);",
    expected: "8 (typed)",
  },
  {
    section: "sec-atomics-float-arithmetic",
    title: "Atomic float arithmetic",
    summary: "add and sub extend to the floating-point families, which the existing Atomics could not express.",
    code: "let f: float64 = 1.5;\nAtomics.add(ref f, 2.25);\nconsole.log(f);\nlet g: float64 = 3.5;\nAtomics.sub(ref g, 1.25);\nconsole.log(g);",
    expected: "3.75 (typed)\n2.25 (typed)",
  },
  {
    section: "sec-atomics-compare-exchange-predicate",
    title: "compareExchange swaps on a match",
    code: "let a: uint32 = 1;\nconsole.log(Atomics.compareExchange(ref a, 1, 5), a);\nconsole.log(Atomics.compareExchange(ref a, 1, 9), a);",
    expected: "1 (typed) 5 (typed)\n5 (typed) 5 (typed)",
  },
  {
    section: "sec-atomics-typed-wait",
    title: "wait and notify",
    code: "console.log(typeof Atomics.wait, typeof Atomics.notify);",
    expected: "'function' 'function'",
  },
  {
    section: "sec-threading-synchronization",
    title: "The synchronization primitives",
    code: "console.log(typeof Lock, typeof Condition, typeof ThreadLocal);",
    expected: "'function' 'function' 'function'",
  },
  {
    section: "sec-lock-objects",
    title: "A lock",
    code: "const l = new Lock();\nconsole.log(typeof l.hold, typeof l.acquire, typeof l.asyncHold);",
    expected: "'function' 'function' 'function'",
  },
  {
    section: "sec-lock.prototype.hold",
    title: "hold runs the body under the lock",
    summary: "The lock is taken for the call and released after it, and the body's value is the result.",
    code: 'const l = new Lock();\nconsole.log(l.hold(() => "critical"));',
    expected: "'critical'",
  },
  {
    section: "sec-lock.prototype.acquire",
    title: "acquire hands back a disposable guard",
    code: 'const l = new Lock();\nconst guard = l.acquire();\nconsole.log(typeof guard[Symbol.dispose]);\nguard[Symbol.dispose]();\nconsole.log(l.hold(() => "reacquired"));',
    expected: "'function'\n'reacquired'",
  },
  {
    section: "sec-lock.prototype.asynchold",
    title: "The async form",
    summary: "asyncHold awaits the lock instead of blocking, so it is what an async function uses.",
    code: "const l = new Lock();\nconst p = l.asyncHold(() => 1);\nconsole.log(p instanceof Promise);",
    expected: "true",
  },
  {
    section: "sec-lock-release-ordering",
    title: "Release is ordered",
    summary: "The lock is free again once the guard is disposed, so a second hold succeeds in the same turn.",
    code: 'const l = new Lock();\nconst guard = l.acquire();\nguard[Symbol.dispose]();\nconsole.log(l.hold(() => "first"), l.hold(() => "second"));',
    expected: "'first' 'second'",
  },
  {
    section: "sec-condition-objects",
    title: "A condition",
    code: "const c = new Condition();\nconsole.log(typeof c.wait, typeof c.notify, typeof c.notifyAll);",
    expected: "'function' 'function' 'function'",
  },
  {
    section: "sec-condition.prototype.wait",
    title: "wait is the blocking form",
    summary: "It releases the lock, waits, and reacquires before returning - which is why it takes the lock.",
    code: "const c = new Condition();\nconsole.log(typeof c.wait, c.wait.length >= 1);",
    expected: "'function' true",
  },
  {
    section: "sec-condition.prototype.asyncwait",
    title: "asyncWait is the awaiting form",
    code: "const c = new Condition();\nconsole.log(typeof c.asyncWait);",
    expected: "'function'",
  },
  {
    section: "sec-condition-notify-operations",
    title: "notify and notifyAll",
    summary: "notify wakes one waiter and notifyAll wakes every waiter; each answers how many it woke, so with none waiting both answer zero.",
    code: "const c = new Condition();\nconsole.log(c.notify(), c.notifyAll());",
    expected: "0 0",
  },
  {
    section: "sec-condition-cancellation",
    title: "A wait may be cancelled",
    summary: "The signal that cancels a wait is the same AbortSignal a thread is cancelled with.",
    code: "const c = new AbortController();\nconsole.log(typeof c.signal, c.signal.aborted);",
    expected: "'object' false",
  },
  {
    section: "sec-threadlocal-objects",
    title: "Storage per agent",
    summary: "Reading before writing should answer DefaultValueOf of the element type; the engine answers undefined (KNOWN-DIVERGENCES.md D19).",
    code: "const t = new ThreadLocal.<uint32>();\nt.value = 5;\nconsole.log(t.value);",
    expected: "5",
  },
  {
    section: "sec-threading-parallel-iteration",
    title: "Thread.parallelFor covers the range",
    summary: "Every index in the half-open range runs exactly once; the order across threads is not specified.",
    code: 'var seen = [];\nThread.parallelFor(0, 10, (i) => seen.push(i));\nconsole.log(seen.sort((a, b) => a - b).join(","));',
    expected: "'0,1,2,3,4,5,6,7,8,9'",
  },
  {
    section: "sec-thread-partition",
    title: "An empty or inverted range does nothing",
    code: "var n = 0;\nThread.parallelFor(5, 5, () => { n += 1; });\nThread.parallelFor(5, 2, () => { n += 1; });\nconsole.log(n);",
    expected: "0",
  },
  {
    section: "sec-thread.parallelfor",
    title: "parallelFor answers nothing",
    summary: "It is run for effect, so its result is undefined.",
    code: "console.log(Thread.parallelFor(0, 4, () => {}));",
    expected: "undefined",
  },
  {
    section: "sec-thread.parallelreduce",
    title: "parallelReduce folds, then combines",
    summary: "Each partition folds with the reducer, and the combiner joins the partial results - here the sum to 100.",
    code: "console.log(Thread.parallelReduce(0, 101, 0, (acc, i) => acc + i, (a, b) => a + b));",
    expected: "5050",
  },
  {
    section: "sec-thread.parallelreduce",
    title: "An empty range answers the initial value",
    code: "console.log(Thread.parallelReduce(3, 3, 42, (a, i) => a + i, (a, b) => a + b));",
    expected: "42",
  },
  {
    section: "sec-thread-parallel-errors",
    title: "A throwing body propagates",
    summary: "The error from a partition surfaces out of the parallel call rather than being swallowed.",
    code: 'Thread.parallelFor(0, 4, (i) => { if (i === 2) throw new RangeError("bad index"); });',
    throws: true,
    expected: "",
  },
  {
    section: "sec-thread-pool",
    title: "The pool is an implementation detail",
    summary: "A program names no threads: it asks for parallel iteration and the pool underneath decides the width.",
    code: "console.log(typeof Thread.parallelFor, typeof Thread.parallelReduce);",
    expected: "'function' 'function'",
  },
];
